### PR TITLE
Odpi init

### PR DESCRIPTION
**Pull request by JPWKU**

### CODE REVIEW

**Comment by JPWKU** [comment]
recheck

**Comment by JPWKU** [comment]
recheck

**Comment by JPWKU** [comment]
recheck

**Comment by JPWKU** [comment]
recheck

**Comment by JPWKU** [comment]
recheck

**Review by tykeal — DISMISSED** [review]
The jenkins-scripts are not needed at all if you are using the global-jjb init scripts...

**Review by tykeal — APPROVED** [review]

**Pull request merged**
