### PR TITLE
Change the IMAGE to latest in jenkins-config

### PR DESCRIPTION
**Pull request by schannamallu**
Signed-off-by: Suresh Channamallu <schannamallu@linuxfoundation.org>
#46

### CODE REVIEW

**Comment by schannamallu** [comment]
recheck

**Comment by schannamallu** [comment]
recheck

**Comment by schannamallu** [comment]
recheck

**Comment by schannamallu** [comment]
recheck

**Comment by schannamallu** [comment]
recheck

**Comment by schannamallu** [comment]
recheck

**Comment by schannamallu** [comment]
recheck

**Comment by askb** [comment]
LGTM

**Pull request merged**
