### PR TITLE
add_sonar_job_mvn_parameters

### PR DESCRIPTION
**Pull request by schannamallu**
Signed-off-by: Suresh Channamallu <schannamallu@linuxfoundation.org>
#120 
Modified maven options for pmd scan and increased the build time out option.

### CODE REVIEW

**Comment by schannamallu** [comment]
recheck

**Comment by schannamallu** [comment]
recheck

**Comment by schannamallu** [comment]
recheck

**Comment by schannamallu** [comment]
jjb-deploy recheck

**Comment by schannamallu** [comment]
jjb-deploy recheck

**Review by jwagantall — APPROVED** [review]

**Pull request merged**
