### PR TITLE
Provide vars file for centos-7

### PR DESCRIPTION
**Pull request by JPWKU**
Signed-off-by: Jeremy Phelps <jphelps@linuxfoundation.org>

### CODE REVIEW

**Review by tykeal — COMMENTED** [review]
@JPWKU is this just a symlink to the common-packer vars file?

**Comment by JPWKU** [comment]
No, it's a separate file.  The packer build script allows for setting these
and prioritizes it over the lower level ones in common-packer.

**Comment by zxiiro** [comment]
What's wrong the the one provided by common-packer? We're trying to simplify things and have it all built into common-packer. We even have a script how to share the base image across clouds. Is odpi missing it?

**Comment by tykeal** [comment]
> What's wrong the the one provided by common-packer? We're trying to simplify things and have it all built into common-packer. We even have a script how to share the base image across clouds. Is odpi missing it?

And that is exactly what I was just about to ask

**Comment by JPWKU** [comment]
Yes that is the case, I wasn't able to share.  I'd prefer to use as is
though.

**Comment by JPWKU** [comment]
ie, would prefer not to write a vars file

**Comment by JPWKU** [comment]
@zxiiro share the base image, this isn't needed now.

**Pull request closed without merging**
