### PR TITLE
Add global-jjb at v0.25.1

### PR DESCRIPTION
**Pull request by JPWKU**
Additionally set up global-jjb symlinks and configured initial
defaults.yaml.

Signed-off-by: Jeremy Phelps <jphelps@linuxfoundation.org>

### CODE REVIEW

**Review by tykeal — DISMISSED** [review]

**Comment by tykeal** [comment]
@JPWKU this looks correct to me, but please do the following:

1. Get DCO probot enabled on this (it should be enabled org wide!)
2. Get verify setup in Jenkins so that this actually goes through a verify!

**Review by tykeal — CHANGES_REQUESTED** [review]
This should be merged into the commit that adds it in (yes I'm aware that it's going to cause you to have to rebase things)

**Review by tykeal — CHANGES_REQUESTED** [review]
This should be merged into the commit that adds the network ID

**Comment by JPWKU** [comment]
No worries, I can fix up.

**Comment by JPWKU** [comment]
Reopened under a  new branch

**Pull request closed without merging**
